### ISSUE TITLE
lch() not convert if I use units

### ISSUE THREAD

**Issue by barcia** [csstools/postcss-lab-function#12]
```css
:root {
   --color-primary: lch(44 70 281);
}
```
Converts to:
```css
:root {
    --color-primary: rgb(14, 101, 220);
}
```

But 
```css
:root {
   --color-primary: lch(44% 70 281);
}
```

And
```css
:root {
   --color-primary: lch(44% 70 281deg);
}
```

Not converts to rgb() and mantain lch().

> I am using the PostCSS cli with
> ```json
> "postcss": "^8.3.11",
> "postcss-cli": "^9.0.2",
> "postcss-preset-env": "^6.7.0",
> ```
