### ISSUE TITLE
lab() and lch() not converted

### ISSUE THREAD

**Issue by cawa-93** [csstools/postcss-lab-function#6]
```css
:root {
  --firebrick: lab(40% 56.6 39);
  --firebrick-a50: lch(40% 68.8 34.5 / 50%);
  --gray-40: gray(40);
  --gray-40a50: gray(40 / .5);
}
```
Converted to
```css
:root {
  --firebrick: lab(40% 56.6 39);
  --firebrick-a50: lch(40% 68.8 34.5 / 50%);
  --gray-40: rgb(94,94,94);
  --gray-40a50: rgba(94,94,94, .5);
}
```

Sandbox:
https://runkit.com/cawa-93/5e9331399a729c001a899676
